env:
  SAUCE_USERNAME: "istjs"
  SAUCE_ACCESS_KEY: "51465978-455e-45f1-b5fa-4acdfc2b49e3"
language: node_js
node_js:
  - "0.10"
script:
  - "bash test/sauce_connect_setup.sh"
  - "IST_BUILD_ID=$RANDOM make test-travis"
