<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ist</string>
	</array>
	<key>name</key>
	<string>ist.js template</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.istjs</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.istjs</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{\{</string>
			<key>end</key>
			<string>}}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.istjs</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.istjs</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.istjs</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.istjs</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>#[a-zA-Z_][a-zA-Z0-9_-]*\b</string>
			<key>name</key>
			<string>support.type.istjs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.[a-zA-Z_][a-zA-Z0-9_-]*\b</string>
			<key>name</key>
			<string>support.class.istjs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@[a-zA-Z_][a-zA-Z0-9_-]*\b</string>
			<key>name</key>
			<string>keyword.control.istjs</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.istjs</string>
	<key>uuid</key>
	<string>d8d69e4a-a6a5-4916-9066-b91b35b447a3</string>
</dict>
</plist>
